- name: Inroduction to loops in ansible
  hosts: localhost
  tasks:
    - name: Loop example
      ansible.builtin.debug:
        msg: Fruit Name={{item}}
      loop:
        - banana
        - apple
    - name: Loop example with maps
      ansible.builtin.debug:
        msg: Fruit Name={{item.Name}}, Quantity= {{item.Quantity}}
      loop:
        - {Name:banana, Quantity:10}
        - {Name:apple, Quantity:10}