- name: Introduction to loops in ansible
  hosts: localhost
  tasks:
    - name: Loop example
      ansible.builtin.debug:
        msg: Fruit Name={{item}}
      loop:
        - banana
        - apple
    - name: Loop example with maps
      ansible.builtin.debug:
        msg: Fruit Name={{items.name}}, Quantity= {{items.quantity}}
      loop:
        - {name: banana, quantity: 10}
        - {name: apple, quantity: 10}